### ISSUE TITLE
Search appears to be broken

### ISSUE THREAD

**Issue by axelson** [codeforamerica/honolulu_answers#62]
Even searching for common terms such as "jobs" or "city halls" returns "Sorry, no results found for "jobs". Please try rephrasing your search terms."

**Comment by rbvea** [comment]
@snajmi  that should be fixed, reindexed on searchify and it looks like it's pulling results:

http://hnlanswers.herokuapp.com/search?q=jobs

http://hnlanswers.herokuapp.com/search?q=city+hall

**Comment by snajmi** [comment]
Thanks for getting Search back up, @rbvea . Doesn't seem like Search is returning the right results, though. Something's still broken.
